name: Benchmark

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: |
          chmod +x scripts/benchmark_compare.sh
          bash -eo pipefail scripts/benchmark_compare.sh | tee benchmark_report.md
      - uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- bench-workflow -->'
      - uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body-path: benchmark_report.md
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmark
          path: |
            bench_pr.txt
            bench_main.txt
            benchmark_report.md
