name: golangci-lint

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read
    # Optional: allow read access to pull request. Use with `only-new-issues` option.
    pull-requests: read

env:
    LINT_VERSION: v2.1
    GO_VERSION: stable

jobs:
    golangci-lint:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-go@v6
              with:
                  go-version: ${{ env.GO_VERSION }}
                  cache-dependency-path: |
                      go.sum
            - name: lint ${{ env.GO_VERSION }}
              uses: golangci/golangci-lint-action@v8
              with:
                  version: ${{ env.LINT_VERSION }}
                  only-new-issues: true
