name: Release

on:
    push:
        branches: ["main"]

permissions:
    contents: write
    packages: write

jobs:
    goreleaser:
        if: startsWith(github.event.head_commit.message, 'Merge pull request')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Generate changelog
              uses: goreleaser/goreleaser-action@v5
              with:
                  args: changelog --output=CHANGELOG.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v5
              with:
                  args: release --clean --release-notes=CHANGELOG.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
