name: Release

on:
    push:
        branches: ["main"]
        tags: ["v*"]
    workflow_dispatch:

permissions:
    contents: write
    packages: write

jobs:
    goreleaser:
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') || startsWith(github.event.head_commit.message, 'Merge pull request') || contains(github.event.head_commit.message, '(#')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Run GoReleaser
              if: github.event_name != 'workflow_dispatch'
              uses: goreleaser/goreleaser-action@v6
              with:
                  args: release --clean --release-notes=RELEASE_NOTES.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Run GoReleaser (snapshot)
              if: github.event_name == 'workflow_dispatch'
              uses: goreleaser/goreleaser-action@v6
              with:
                  args: release --clean --release-notes=RELEASE_NOTES.md --skip-publish --snapshot
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
